### ISSUE TITLE
403报错

### ISSUE THREAD

**Issue by HaoxuanYu2007** [orzchen/icpApi#1]
![image](https://github.com/orzchen/icpApi/assets/137419260/ffef2477-6f1e-4a72-9f02-523605bac0fa)

**Comment by orzchen** [comment]
官方改了接口，已经G了，最近没时间修改Orz

**Comment by HaoxuanYu2007** [comment]
> 官方改了接口，已经G了，最近没时间修改Orz

能麻烦修改下吗 可以给点资金支持

**Comment by orzchen** [comment]
如果你急用的话，可以看看站长的API接口，有白嫖额度的。https://api.chinaz.com/

**Comment by orzchen** [comment]
参考站长的主办单位备案API：
https://api.chinaz.com/ApiDetails/NewSponsorUnit

https://api.chinaz.com/ApiDetails/SponsorUnit
